const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const html=fs.readFileSync(process.env.TRACKER_HTML || path.join(__dirname,'../match-tracker.html'),'utf8');
const slice=(a,b)=>html.slice(html.indexOf(a),html.indexOf(b,html.indexOf(a)));
function setup(db={}) {
 const store=new Map(),elements=new Map(); let serial=0;
 const copy=x=>x==null?null:JSON.parse(JSON.stringify(x));
 const api={ref(key){return {once:async()=>({val:()=>copy(db[key])}),set:async value=>{if(db.fail || (db.failHistory && key.startsWith('matchHistory/')))throw Error('denied');db[key]=copy(value)},transaction:async fn=>{if(db.fail)throw Error('denied');const value=fn(copy(db[key]));if(value===undefined)return {committed:false};db[key]=copy(value);return {committed:true}}}}};
 const c=vm.createContext({console,URLSearchParams,window:{location:{search:''},addEventListener(){}},navigator:{onLine:true},crypto:{randomUUID:()=>`id-${++serial}-${Math.random()}`},setTimeout,clearTimeout,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k),key:i=>[...store.keys()][i],get length(){return store.size}},document:{getElementById(id){if(!elements.has(id))elements.set(id,{style:{},value:'Home vs. Away',textContent:'12.09.2026'});return elements.get(id)}},firebase:{database:Object.assign(()=>api,{ServerValue:{TIMESTAMP:123}})},firebaseReady:true,activeMatchId:1,homeScore:2,awayScore:5,isHomeTeam:false,events:[{id:4,minute:5,team:'away'}],squad:[],schedule:[{id:1,opponent:'Home',isHome:false}],timerBase:null,timerOffset:300,homeLogo:'',awayLogo:'',homeColor:'',awayColor:'',elapsedSeconds:()=>300,getMatchTeams:()=>({home:'Home',away:'Away'}),getOurTeamName:()=> 'Away',showToast(){},applyTeamColors(){},updateScoreLabels(){},updateGoalButtons(){},updateScore(){},renderEvents(){},updateEndMatchBtn(){},updateTimerDisplay(){},startTimerLoop(){},stopTimerLoop(){},switchTab(){},resolveLogos(){},renderSpielplan(){},save(){},pauseTimer(){}});
 vm.runInContext(slice('// Durable match state:', '// ─── INIT ─')+slice('function retryPendingMatches()', '// ─── FIREBASE GLOBAL SYNC')+slice('async function startMatchFromSchedule(', 'function updateEndMatchBtn()'),c);
 vm.runInContext('storageReady=true; matchRevisions[1]=null;',c);
 return {c,store,db,flush:()=>vm.runInContext('matchWriteQueue',c),run:s=>vm.runInContext(s,c),status:()=>elements.get('storageStatus')?.textContent};
}
test('snapshot keeps original ID and score when state changes before upload',async()=>{const x=setup();x.c.syncToFirebase();x.c.activeMatchId=null;x.c.homeScore=0;x.c.events=[];await x.flush();assert.equal(x.db['matches/1'].homeScore,2);assert.equal(x.db['matches/1'].events.length,1);assert(!x.db['matches/null']);});
test('finalization writes the full result and events, survives duplicate calls',async()=>{const x=setup();x.c.endCurrentMatch();await x.flush();assert.equal(x.db['matches/1'].awayScore,5);assert(x.db['matches/1'].matchFinished);assert.equal(x.db['matches/1'].events.length,1);assert.equal(x.c.activeMatchId,null);});
test('restarting an existing fixture resumes instead of resetting',async()=>{const x=setup({'matches/2':{homeTeam:'Home',awayTeam:'Away',homeScore:2,awayScore:5,events:[{id:4}],revision:'old',timerOffset:300}});x.c.activeMatchId=null;x.c.schedule.push({id:2,opponent:'Home'});await x.c.startMatchFromSchedule(2);assert.equal(x.c.awayScore,5);assert.equal(x.c.events.length,1);assert.equal(x.run('matchRevisions[2]'),'old');});
test('completed fixture cannot restart; another active match cannot be replaced',async()=>{const x=setup({'matches/2':{matchFinished:true,homeScore:2}});x.c.schedule.push({id:2});await x.c.startMatchFromSchedule(2);assert.equal(x.c.activeMatchId,1);x.c.activeMatchId=null;await x.c.startMatchFromSchedule(2);assert.equal(x.c.activeMatchId,null);});
test('offline start leaves state intact',async()=>{const x=setup();x.c.activeMatchId=null;x.c.navigator.onLine=false;await x.c.startMatchFromSchedule(1);assert.equal(x.c.awayScore,5);assert.equal(x.c.activeMatchId,null);});
test('stale device cannot replace newer server state, both snapshots archived',async()=>{const x=setup({'matches/1':{homeScore:2,awayScore:5,revision:'other'}});x.c.homeScore=0;x.c.awayScore=0;x.c.syncToFirebase();await x.flush();assert.equal(x.db['matches/1'].awayScore,5);assert(x.run('matchConflict'));assert(Object.keys(x.db).filter(k=>k.startsWith('matchHistory/')).length===2);assert(x.store.has('mt_pending_1'));});
test('legacy match with a timestamp is protected from an uninitialized client',async()=>{const x=setup({'matches/1':{homeScore:2,awayScore:5,updatedAt:999}});x.c.syncToFirebase();await x.flush();assert.equal(x.db['matches/1'].updatedAt,999);assert(x.run('matchConflict'));});
test('failed writes retain local outbox and show failure; retry uploads it',async()=>{const x=setup({fail:true});x.c.syncToFirebase();await x.flush();assert(x.store.has('mt_pending_1'));assert.match(x.status(),/fehlgeschlagen/);delete x.db.fail;x.c.retryPendingMatches();await x.flush();assert.equal(x.db['matches/1'].awayScore,5);assert(!x.store.has('mt_pending_1'));});
test('unavailable server history does not block the live match update',async()=>{const x=setup({failHistory:true});x.c.syncToFirebase();await x.flush();assert.equal(x.db['matches/1'].awayScore,5);assert(!x.store.has('mt_pending_1'));assert.match(x.status(),/Live-Update aktiv/);});
test('consecutive saves advance revisions without conflicting with themselves',async()=>{const x=setup();x.c.syncToFirebase();x.c.awayScore=6;x.c.syncToFirebase();await x.flush();assert.equal(x.db['matches/1'].awayScore,6);assert(!x.run('matchConflict'));assert([...x.store.keys()].some(k=>k.startsWith('mt_history_1_')));});
test('archive failure blocks replacing latest server state',async()=>{const x=setup({fail:true,'matches/1':{awayScore:5}});x.c.syncToFirebase();await x.flush();assert.equal(x.db['matches/1'].awayScore,5);});

test('offline reload retains the last acknowledged revision for subsequent changes',async()=>{const x=setup({'matches/1':{revision:'saved',awayScore:5}});x.store.set('mt_revision_1',JSON.stringify('saved'));x.run('delete matchRevisions[1]');x.c.awayScore=6;x.c.syncToFirebase();await x.flush();assert.equal(x.db['matches/1'].awayScore,6);assert(!x.run('matchConflict'));});
test('retrying an acknowledged old job does not delete a newer pending change',async()=>{const x=setup({'matches/1':{revision:'old',awayScore:5}});x.store.set('mt_pending_1',JSON.stringify({id:'1',revision:'new',data:{awayScore:6}}));await x.c.writeMatchJob({id:'1',revision:'old',data:{awayScore:5}});assert.equal(JSON.parse(x.store.get('mt_pending_1')).revision,'new');});
test('finished server record rejects later writes even with matching revision',async()=>{const x=setup({'matches/1':{revision:'final',awayScore:5,matchFinished:true}});x.run("matchRevisions[1]='final'");x.c.awayScore=0;x.c.syncToFirebase();await x.flush();assert.equal(x.db['matches/1'].awayScore,5);assert(x.run('matchConflict'));});

async function boot(x) {
 x.c.loadTraining=async()=>{};x.c.checkAccess=()=>true;x.c.initFirebase=()=>true;
 x.c.loadGlobalFromFirebase=cb=>{x.boot=cb();};
 vm.runInContext(html.slice(html.lastIndexOf('(function() {'),html.lastIndexOf('</script>')),x.c);
 await x.boot;
}
test('reload adopts saved score without writing a zero baseline; preserves local copy',async()=>{const data={homeTeam:'Home',awayTeam:'Away',homeScore:2,awayScore:5,revision:'stored',events:[{id:1}]};const x=setup({matches:{1:data}});x.c.homeScore=0;x.c.awayScore=0;await boot(x);assert.equal(x.c.awayScore,5);assert.equal(x.db.matches[1].revision,'stored');assert(!x.db['matches/1']);assert(x.store.has('mt_match_1'));});
test('completed match is recovered into an empty schedule during reload',async()=>{const x=setup({matches:{1:{homeTeam:'Home',awayTeam:'Away',homeScore:2,awayScore:5,matchFinished:true,events:[{id:1}],isHomeTeam:false}}});x.c.schedule=[];await boot(x);assert.equal(x.c.schedule[0].result.away,5);assert.equal(x.c.activeMatchId,null);assert.equal(x.c.schedule[0].result.events.length,1);});

test('finish then start another fixture preserves the completed result and events',async()=>{const x=setup();x.c.resetTimer=()=>{};x.c.schedule.push({id:2,opponent:'Next',isHome:true});x.c.endCurrentMatch();await x.c.startMatchFromSchedule(2);await x.flush();assert.equal(x.c.activeMatchId,2);assert.equal(x.c.homeScore,0);assert.equal(x.c.events.length,0);assert.equal(x.db['matches/1'].awayScore,5);assert(x.db['matches/1'].matchFinished);assert.equal(x.db['matches/1'].events.length,1);assert.equal(x.c.schedule[0].result.away,5);});
test('a conflict on the previous match does not block a different fixture',async()=>{const x=setup({'matches/1':{revision:'other',awayScore:5}});x.c.resetTimer=()=>{};x.c.schedule.push({id:2,opponent:'Next'});x.c.endCurrentMatch();await x.flush();assert(x.run('matchConflict'));await x.c.startMatchFromSchedule(2);assert.equal(x.c.activeMatchId,2);});
test('failed local final backup does not discard the active match',()=>{const x=setup();x.c.localStorage.setItem=()=>{throw Error('quota')};x.c.endCurrentMatch();assert.equal(x.c.activeMatchId,1);assert.equal(x.c.awayScore,5);});
